* A bare skeleton doom
  I have used Emacs Doom for a while. I move to my own Dotfiles because I wanted less Doom magic to happen in my Editor and I wanted to have full control and understanding of my editor.

  I try to have Doom like functionality with the least amount of customizations. I mostly focus on the functionality that I have used extensively ( so it probably excludes most of Doom's features ).

  The packages constitutes a subset of Doom's packages.

  I have coppied some functions from Doom ( e.g. doom escape, org mode keywords, and other features that I commonly use ) from Emacs Doom to make my life easier.

* Structure
** core/package.el
   This file gets evaluated first. It has all the packages that are installed.
** core/core.el
   This file gets evaluated second. It has functions that I use and non-package related customization (i.e. builtin stuff). So far I have used it to put stuff that are not packages or keybindings.
** core/keybindings.el
   This file gets evaluated last. It contains all the key bindings.
