* A bare skeleton doom
  I have used Emacs Doom for a while. I moved to my own Dotfiles because I wanted less Doom magic and full control of my editor.

  I try to have Doom like functionality with the least amount of configuration. I mostly focus on the functionality that I have used extensively ( so it probably excludes most of Doom's features ).

  I have copied some functions from Doom ( e.g. doom escape, org mode keywords, packages, and other features that I commonly use ) from Doom to make it have a "doomish" feel.

* Structure
** core/package.el
   This file gets evaluated first. It has all installed packages and their configurations.
** core/core.el
   This file gets evaluated second. It has functions that I use and non-package related configurations (i.e. builtin stuff). So far I have used it to put stuff that are not packages or keybindings.
** core/keybindings.el
   This file gets evaluated last. It contains all the key bindings.

* Roadmap
  1. [ ] lsp support.
  2. [ ] Workspace support
 
